branch-defaults:
  master:
    environment: king-of-gym-env
    group_suffix: null
global:
  application_name: king-of-gym
  default_ec2_keyname: king-of-gym-eb
  default_platform: python3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
